.\" $Id: olymp.1,v 1.7 2010-07-16 21:31:19 grahn Exp $
.\" $Name:  $
.\" 
.\"
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.TH olymp 1 "NOV 2019" "Olymp" "User Manuals"
.
.SH "NAME"
olymp \- enumerate and/or rename digital camera photos
.
.SH "SYNOPSIS"
.B olymp
.RB [ \-e ]
.RB [ \-W ]
.I file
\&...
.br
.B olymp
.B --help
.br
.B olymp
.B --version
.
.SH "DESCRIPTION"
.
Digital cameras
store images in files with pretty silly names, like
.BR P7050124.JPG .
This translates to
\[lq]the current year,
month 7,
day 05,
image serial number 0124\[rq].
Stored inside the image, as
.SM EXIF
data, is the full date, along with the time of day.
.LP
This utility prints a more readable variation of the file name,
along with the date and time and possibly a GPS coordinate, based on the
.SM EXIF
information.
Optionally, if the
.B \-e
option is given,
the file is renamed in the same fashion.
.LP
An output entry may look like:
.IP
.ft CW
.nf
2019-10-19_0074.jpg   \fInew filename, with no directory part\fP
2019-10-19 14:56      \fPdate and time\fP
.fi
.LP
The new file name assures that it sorts correctly in e.g. directory listings,
and guarantees uniqueness (at least if you only use one camera on
any particular day).
.PP
The date and time come, as noted, from the
.SM EXIF
information, i.e. from the camera's clock.
So the clock has to be set correctly for this information to be useful.
The time recorded in the file is
.I local
time \- with no timezone information \- so that's what's printed here, too.
For most purposes, that's acceptable.
.
.SS "GPS coordinates"
.
If the image is geotagged, i.e. contains Exif/GPS information from a
GPS receiver or similar, the camera's coordinate is also included in the output.
For example:
.IP
.ft CW
.nf
2018-07-24_2482.jpg     2018-07-24_2482.jpg
2018-07-24 06:33        2018-07-24 06:33
{65.6542 14.5360}       {7281446 478656}
.fi
.LP
The leftmost version includes a
.SM "\fBWGS\ 84"
coordinate, in degrees, rounded to four decimals.
The version to the right includes the same coordinate expressed in
.SM "\fBSWEREF\ 99\ TM"
with 1\ m resolution: seven digits northing, six digits easting.
.PP
The coordinates are printed this way irrespectively of the format used in the image.
The various error estimates which may or may not be encoded into
the image are also ignored \- so it's up to the reader to remember that
there's an uncertainty involved.
.
.SS "Input file names"
.
All digital cameras I've seen encode an image serial number into the file name,
after some kind of prefix.
The only useful part of the file name is this serial number \- which
seems to exist only here, not in the EXIF information.
.PP
.B Olymp
chooses the last sequence of digits in the file name, and assumes the four last
of these form the serial number.
Thus this utility correctly handles the following naming conventions,
in upper- or lowercase:
.
.IP "\fBp\fImddserial\fP.jpg" 25x
Olympus, Panasonic; others?
.IP "\fBdsc\fIserial\fP.jpg"
Various camera makers.
.IP "\fBdscn\fIserial\fP.jpg"
At least Nikon (is the
.B N
for Nikon, perhaps?)
.IP "\fBimag\fIserial\fP.jpg"
At least some camera-equipped phones
.IP "\fIyyyy-mm-dd_serial\fB.jpg"
its own format
.
.PP
Some of these naming conventions are probably standardized.
.
.SH "OPTIONS"
.
.BP \-e
Perform actual renaming of files; don't just list new names.
.IP
Renaming is always safe.
Existing files are never overwritten, and files which are already
correctly named aren't touched at all.
.
.BP \-W
Always print coordinates in
.SM "\fBWGS\ 84\fP."
By default,
.SM "\fBSWEREF\ 99\ TM"
is used for locations which seem like they could be in Sweden.
.
.SH "NOTES"
.
.B Olymp
does not use the time stamp of the file.
Nor does it use the current file name, except for the image serial number.
.
.SH "BUGS"
.
.IP \- 2m
When an image contains GPS data, chances are it also contains an accurate
GPS timestamp.
.B Olymp
doesn't use it, and doesn't warn if the camera's clock disagrees with it.
.
.IP \-
As mentioned above, showing coordinates with high resolution without also giving
an estimated error can be misleading.
It's not clear to me how to get an understandable error estimate from a camera,
and anyway there is no standard notation for precision in
.SM "SWEREF\ 99\ TM."
.
.IP \-
People outside Sweden have no use for
.SM "\fBSWEREF\ 99\ TM"
coordinates.
.
.SH "AUTHOR"
J\(:orgen Grahn \[fo]grahn+src@snipabacken.se\[fc].
.PP
Conversion to
.SM "SWEREF\ 99"
coordinates
relies on the
.B libproj
library, also known as
.BR \s-1PROJ.4\s0 ,
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
